name: Test and release

on: 
  workflow_dispatch:
    inputs:
      DO_RELEASE:
        description: 'Should the APK be pre-release on Github repository?'
        required: true
        default: true 
        type: boolean

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # The following step as short on disk space
      # docs here: https://github.com/marketplace/actions/maximize-build-disk-space
      - name: Maximize build space 🪶
        uses: easimon/maximize-build-space@master
        with:
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
          # We can afford to uninstall android & dotnet as game-ci relies on docker containers
          remove-android: true
          remove-dotnet: true
          root-reserve-mb: 20480 

      # Checkout
      - name: Checkout repository 📥
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: '1'

      # Cache
      #- uses: actions/cache@v3
      #  with:
      #    path: Library
      #    key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
      #    restore-keys: |
      #      Library-

      # Test
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v4
      #  env:
      #    UNITY_LICENSE: ${{ secrets.ARTHUR_UNITY_PERSONAL_LICENSE }}
      #  with:
      #    githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project 👷
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.ARTHUR_UNITY_PERSONAL_LICENSE }}
          UNITY_EMAIL: ${{ secrets.ARTHUR_UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.ARTHUR_UNITY_PASSWORD }}
        with:
          targetPlatform: Android

      # Output
      - name: Save built artefact 📦
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

      - name: Publish alpha to Github 🎉
        uses: svenstaro/upload-release-action@2.9.0
        if: "${{ github.event.inputs.DO_RELEASE }}"
        with:
          body: |
            Alpha release for SIMPLE's CTU TowerDefense game. Please test and report issues.
            It has been built on the commit ${{ github.event.pull_request.head.sha }}.
          file: |
            build/Android/Android.apk
            Android/Android.apk
          file_glob: true
          make_latest: false
          promote: false
          prerelease: true
          overwrite: true
          release_name: Alpha Version ${{ github.event.pull_request.head.sha }}
          repo_token: ${{ secrets.SIMPLE_ORGA_TOKEN }}
          